version: '3.7'
services:
  cassandra:
    image: bitnami/cassandra:latest
    environment:
    ports:
      - "7199:7199"
      - "7000:7000"
      - "7001:7001"
      - "9160:9160"
      - "9042:9042"
    volumes: 
      - cassandradb:/bitnami
volumes:
  cassandradb: